# docker-compose.yml
services:
  postgres:
    image: postgres:16-alpine
    container_name: realtX_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: realtX
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
